# name: Random Cron
# on:
#     workflow_run:
#       workflows: ["HidenCloud Auto Renew (Python)"]
#       types:
#         - completed
# jobs:
#     repo-sync:
#       if: github.event.workflow_run.conclusion == 'success'
#       runs-on: ubuntu-latest
#       timeout-minutes: 3

#       steps:
#         - uses: actions/checkout@v4
#           with:
#             token: ${{ secrets.PAT }}

#         - name: random cron
#           shell: bash
#           run: |
#             sed -i -E "s/(- cron: ')[0-9]+( [^[:space:]]+ \* \* \*')/\1$(($RANDOM % 59))\2/g" .github/workflows/main.yml

#             git config user.name github-actions
#             git config user.email github-actions@github.com
#             git add .github/workflows/main.yml

#             git diff --cached --quiet && exit 0

#             git commit -m "random cron"
#             git push origin HEAD
